# version: "3.8"

services:
  backend:
    image: memorize-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # env_file:
    #   - ./backend/.env
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: some-secret-key
      DATABASE_URL: your-database-url
  frontend:
    image: memorize-frontend
    build:
      context: ./frontend/gallery
    # env_file:
    #   - ./frontend/gallery/.env
    ports:
      - "3001:3001"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      VITE_BACKEND_URL: http://localhost:8080

    depends_on:
      - backend
