# version: "3.8"

services:
  backend:
    image: memorize-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
  frontend:
    image: memorize-frontend
    build:
      context: ./frontend/gallery
    ports:
      - "3000:3000"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    depends_on:
      - backend
