# version: "3.8"

services:
  backend:
    image: memorize-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # env_file:
    #   - ./backend/.env
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
  frontend:
    image: memorize-frontend
    build:
      context: ./frontend/gallery
      args:
        # The value for GIT_COMMIT_TAG is pulled from the host's BUILD_TAG variable
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    # env_file:
    #   - ./frontend/gallery/.env
    ports:
      - "3001:3001"
    environment:
      # BACKEND_HOST: backend
      # BACKEND_PORT: 8081
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}

    depends_on:
      - backend
